---
remotes:
  primary: git@github.com:destructuring/definition-basebox
  secondary: git@bitbucket.org:destructuring/definition-basebox
  sh: https://github.com/destructuring/jason
  bump: https://github.com/destructuring/mixin-bump
