#!/bin/bash

#/ NAME
#/     bundle-ruby -- bundle release with bundler and rvm
#/
#/ SYNOPSIS
#/     
#/     bundle-ruby ruby_loader ruby bundler_options


# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"

# entry point
function main {
  set -x
  unset BUNDLE_BIN_PATH BUNDLE_GEMFILE RUBYOPTS
  env | sort
  which ruby
  which gem
  which bundle
  if ! bundle check; then
    bundle install --local --path vendor/bundle "$@"
  fi
  set +x
}

require sub "$BASH_SOURCE" "$@"
